# Generated by Django 5.0.2 on 2024-05-21 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_alter_scheduledcourse_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('scheduled_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_courses', to='courses.scheduledcourse')),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activity',
                'db_table': 'activity',
                'ordering': ['id'],
            },
        ),
    ]
