# Generated by Django 5.0.2 on 2024-06-07 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('courses', '0003_alter_scheduledcourse_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEvaluationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='activities.activity')),
                ('version_evaluation_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_version_details', to='courses.evaluationversiondetail')),
            ],
            options={
                'verbose_name': 'activity_evaluation_detail',
                'verbose_name_plural': 'activity_evaluation_detail',
                'db_table': 'activity_evaluation_detail',
                'ordering': ['id'],
            },
        ),
    ]
