# Generated by Django 5.0.2 on 2024-08-20 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activityevaluationdetail'),
        ('courses', '0004_studentenrolledcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='scheduled_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_scheduled_courses', to='courses.scheduledcourse'),
        ),
        migrations.CreateModel(
            name='GradeDetailLearningOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_evalution_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_evaluation_details', to='activities.activityevaluationdetail')),
                ('enrolled_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrolled_courses', to='courses.studentenrolledcourse')),
            ],
            options={
                'verbose_name': 'grade_detail_learning_outcome',
                'verbose_name_plural': 'grade_detail_learning_outcome',
                'db_table': 'grade_detail_learning_outcome',
                'ordering': ['id'],
            },
        ),
    ]
