# Generated by Django 5.0.2 on 2024-03-02 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2')])),
            ],
            options={
                'verbose_name': 'academic_period',
                'verbose_name_plural': 'academic_period',
                'db_table': 'academic_period',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True)),
                ('credit', models.BigIntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_period', to='courses.academicperiod')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('version_date', models.DateField()),
                ('course', models.ManyToManyField(related_name='outcome_details', to='courses.course')),
            ],
            options={
                'verbose_name': 'learning_outcome',
                'verbose_name_plural': 'learning_outcome',
                'db_table': 'learning_outcome',
                'ordering': ['id'],
            },
        ),
    ]
