# Generated by Django 5.0.2 on 2024-04-19 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2024)),
                ('semester', models.IntegerField(choices=[(1, '1'), (2, '2')])),
            ],
            options={
                'verbose_name': 'academic_period',
                'verbose_name_plural': 'academic_period',
                'db_table': 'academic_period',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('credit', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'course',
                'db_table': 'course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutCome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'learning_outcome',
                'verbose_name_plural': 'learning_outcome',
                'db_table': 'learning_outcome',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professor',
                'db_table': 'professor',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_courses', to='courses.course')),
            ],
            options={
                'verbose_name': 'evaluation_version',
                'verbose_name_plural': 'evaluation_version',
                'db_table': 'evaluation_version',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_outcomes', to='courses.learningoutcome')),
            ],
            options={
                'verbose_name': 'percentage',
                'verbose_name_plural': 'percentage',
                'db_table': 'percentage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationVersionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_evaluation_versions', to='courses.evaluationversion')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_outcomes', to='courses.learningoutcome')),
                ('percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_percentages', to='courses.percentage')),
            ],
            options={
                'verbose_name': 'evaluation_version_detail',
                'verbose_name_plural': 'evaluation_version_detail',
                'db_table': 'evaluation_version_detail',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('evaluation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_evaluation_versions', to='courses.evaluationversion')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_academic_periods', to='courses.academicperiod')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='courses.professor')),
            ],
            options={
                'verbose_name': 'scheduled_course',
                'verbose_name_plural': 'scheduled_course',
                'db_table': 'scheduled_course',
                'ordering': ['id'],
            },
        ),
    ]
