# Generated by Django 5.0.2 on 2024-04-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['id'], 'verbose_name': 'professor', 'verbose_name_plural': 'professor'},
        ),
        migrations.AlterModelTable(
            name='professor',
            table='professor',
        ),
    ]
