# Generated by Django 5.0.2 on 2024-03-08 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'evaluation_version',
                'verbose_name_plural': 'evaluation_version',
                'db_table': 'evaluation_version',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='period',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='course',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='learningoutcome',
            name='version_date',
        ),
        migrations.CreateModel(
            name='Percentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('porcentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcome', to='courses.learningoutcome')),
            ],
            options={
                'verbose_name': 'percentage',
                'verbose_name_plural': 'percentage',
                'db_table': 'percentage',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='courses.course')),
                ('evaluation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_version', to='courses.evaluationversion')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_period', to='courses.academicperiod')),
            ],
            options={
                'verbose_name': 'scheduled_course',
                'verbose_name_plural': 'scheduled_course',
                'db_table': 'scheduled_course',
                'ordering': ['id'],
            },
        ),
    ]
