# Generated by Django 5.0.2 on 2024-04-29 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_evaluationversion_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledcourse',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='academicperiod',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
