# Generated by Django 5.0.2 on 2024-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_evaluationversion_remove_course_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='end_date',
            field=models.DateField(null=True),
        ),
    ]
