# Generated by Django 5.0.2 on 2024-03-12 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_percentage_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='percentage',
            old_name='porcentage',
            new_name='percentage',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='percentage',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percentage_outcomes', to='courses.learningoutcome'),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_courses', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='evaluation_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_evaluation_versions', to='courses.evaluationversion'),
        ),
        migrations.AlterField(
            model_name='scheduledcourse',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_academic_periods', to='courses.academicperiod'),
        ),
        migrations.CreateModel(
            name='EvaluationVersionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_evaluation_versions', to='courses.evaluationversion')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_outcomes', to='courses.learningoutcome')),
                ('percentage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_details_percentages', to='courses.percentage')),
            ],
            options={
                'verbose_name': 'evaluation_version_detail',
                'verbose_name_plural': 'evaluation_version_detail',
                'db_table': 'evaluation_version_detail',
                'ordering': ['id'],
            },
        ),
    ]
