# Generated by Django 5.0.2 on 2024-03-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_porcentage_percentage_percentage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningoutcome',
            old_name='name',
            new_name='code',
        ),
    ]
