# Generated by Django 5.0.2 on 2024-10-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_studentenrolledcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrolledcourse',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
