# Generated by Django 5.0.2 on 2024-03-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_rename_name_learningoutcome_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='percentage',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
