# Generated by Django 5.0.2 on 2024-11-07 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_set_active_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrolledcourse',
            name='end_grade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrolledcourse',
            unique_together={('student', 'scheduled_course')},
        ),
    ]
